language: ruby
rvm:
  - 1.9.2
before_script:
  - "rake db:migrate"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
branches:
  only:
    - "master"
notifications:
  email:
    - "rodrigomb@gmail.com"
